### ISSUE TITLE
Missing data preparation steps notebook?

### ISSUE THREAD

**Issue by windix** [paragao/reinvent2019-ret310#1]
From the main notebook:

> As for all Machine Learning solutions, data preparation is a key step to achieve higher quality on the final solution. For the data preparation steps taken on this exercise, please check the notebook "RET310 - Data preparation steps.ipynb" also present on this repository.

But cannot find "RET310 - Data preparation steps.ipynb"?

**Comment by paragao** [comment]
Hi, first of all, so sorry for the long delay in this answer. I hope it still finds you interested in it. I have just uploaded the Data preparation steps file.
